name: Build and Deploy My App

on:
  push:
    branches: [main]

jobs:


  build:
  
    name: This is the build job
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [Front-1, Front-2]

    steps:
      - name: Step 1
        run:
          echo "Task performed at the build step on front 1 and 2"
  


 