name: Build and Deploy My App

on:
  push:
    branches: [main]

jobs:


  build:
  
    name: This is the build job
    runs-on: self-hosted

    steps:
      - name: Step 1
        run:
          echo "Task performed at the build step"
  


 