name: Build and Deploy My App

on:
  push:
    branches: [main]

jobs:


  build:
  
    name: This is the build job
    runs-on: Front

    steps:
      - name: Step 1
        run:
          echo "Task performed at the build step on front 1"
  


 