name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
  
    name: This is the build job
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run:
          echo "Task performed at the build step"
  
  deploy:
    needs: [build]

    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      run: 
        echo "Task performed at the build step"

 